[build]
command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "8.1" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = index
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "/*"
to = "/404"
status = 404